application: wide-plating-97021
version: assignment3final
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.application

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: MySQLdb
  version: latest
