application: kamujupython
version: assignment7
runtime: python27
api_version: 1
threadsafe: yes
instance_class: B2
basic_scaling:
  max_instances: 11
  idle_timeout: 10m

handlers:
- url: .*
  script: main.application
  
- url: /profile/.*
  script: user_profile.app
  login: required

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: MySQLdb
  version: latest
